version: "3.8"
services:

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Shanghai
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_AUTH}